name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create secrets.env.js
        shell: bash
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          INVALID_USER_EMAIL: ${{ secrets.INVALID_USER_EMAIL }}
          INVALID_USER_PASSWORD: ${{ secrets.INVALID_USER_PASSWORD }}
        run: |
          cat <<EOF > secrets.env.js
          const secrets = {
              "userEmail": "$USER_EMAIL",
              "userPassword": "$USER_PASSWORD",
              "invalidUserEmail": "$INVALID_USER_EMAIL",
              "invalidUserPassword": "$INVALID_USER_PASSWORD"
          }
          export default secrets;
          EOF

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # We installed cypress locally, so we can use the local install
          install: true
          # Start command is not needed if you don't have a dev server dependency
          # If your app needs to be running, add 'start: npm run dev' here
